#ifndef __SHAPE_CONTAINER_H__
#define __SHAPE_CONTAINER_H__

#include "mclang.h"

#define SHAPE_CONTAINER_NAME              shape
#define SHAPE_CONTAINER_FUNC_LIST_NAME    shape_funclist

/* 容器 */
CONTAINER(SHAPE_CONTAINER_NAME) START
    // 函数成员
    CONTAINER_FUNC_LIST_PTR(SHAPE_CONTAINER_FUNC_LIST_NAME);
    // 变量成员
    INT32 width, height;
END;

/* 函数列表盒子 */
CONTAINER_FUNC_LIST_BOX(SHAPE_CONTAINER_FUNC_LIST_NAME) START
    CONTAINER_CONSTRUCTOR_PTR(SHAPE_CONTAINER_NAME);
    CONTAINER_DESTRUCTOR_PTR(SHAPE_CONTAINER_NAME);
    
    CONTAINER_FUNC_PTR(INT32, SHAPE_CONTAINER_NAME, get_width);
    CONTAINER_FUNC_ARGS_PTR(INT32, SHAPE_CONTAINER_NAME, set_width, INT32 widht);
    CONTAINER_FUNC_PTR(INT32, SHAPE_CONTAINER_NAME, get_area);
    CONTAINER_FUNC_PTR(INT32, SHAPE_CONTAINER_NAME, show_area);
END;

/* 导出函数列表 */
EXTERN CONTAINER_FUNC_LIST(SHAPE_CONTAINER_FUNC_LIST_NAME);

#endif  /* __SHAPE_CONTAINER_H__ */